const docList = [
  {
    zh: "Hello World",
    en: "Hello World",
    link: "01-hello-world.md",
    source: "01-hello-world.go",
  },
  { zh: "值", en: "Values", link: "02-values.md", source: "02-values.go" },
  {
    zh: "变量",
    en: "Variables",
    link: "03-variables.md",
    source: "03-variables.go",
  },
  {
    zh: "常量",
    en: "Constants",
    link: "04-constants.md",
    source: "04-constants.go",
  },
  { zh: "循环", en: "For", link: "05-for.md", source: "05-for.go" },
  {
    zh: "If/Else语句",
    en: "If/Else",
    link: "06-if-else.md",
    source: "06-if-else.go",
  },
  {
    zh: "Switch语句",
    en: "Switch",
    link: "07-switch.md",
    source: "07-switch.go",
  },
  { zh: "数组", en: "Arrays", link: "08-arrays.md", source: "08-arrays.go" },
  { zh: "切片", en: "Slices", link: "09-slices.md", source: "09-slices.go" },
  { zh: "映射", en: "Maps", link: "10-maps.md", source: "10-maps.go" },
  { zh: "范围", en: "Range", link: "11-range.md", source: "11-range.go" },
  {
    zh: "函数",
    en: "Functions",
    link: "12-functions.md",
    source: "12-functions.go",
  },
  {
    zh: "多返回值",
    en: "Multiple Return Values",
    link: "13-multiple-return-values.md",
    source: "13-multiple-return-values.go",
  },
  {
    zh: "可变参数函数",
    en: "Variadic Functions",
    link: "14-variadic-functions.md",
    source: "14-variadic-functions.go",
  },
  {
    zh: "闭包",
    en: "Closures",
    link: "15-closures.md",
    source: "15-closures.go",
  },
  {
    zh: "递归",
    en: "Recursion",
    link: "16-recursion.md",
    source: "16-recursion.go",
  },
  {
    zh: "指针",
    en: "Pointers",
    link: "17-pointers.md",
    source: "17-pointers.go",
  },
  {
    zh: "字符串和符文",
    en: "Strings and Runes",
    link: "18-strings-and-runes.md",
    source: "18-strings-and-runes.go",
  },
  {
    zh: "结构体",
    en: "Structs",
    link: "19-structs.md",
    source: "19-structs.go",
  },
  { zh: "方法", en: "Methods", link: "20-methods.md", source: "20-methods.go" },
  {
    zh: "接口",
    en: "Interfaces",
    link: "21-interfaces.md",
    source: "21-interfaces.go",
  },
  {
    zh: "结构体嵌套",
    en: "Struct Embedding",
    link: "22-struct-embedding.md",
    source: "22-struct-embedding.go",
  },
  {
    zh: "泛型",
    en: "Generics",
    link: "23-generics.md",
    source: "23-generics.go",
  },
  {
    zh: "错误处理",
    en: "Errors",
    link: "24-errors.md",
    source: "24-errors.go",
  },
  {
    zh: "Go协程",
    en: "Goroutines",
    link: "25-goroutines.md",
    source: "25-goroutines.go",
  },
  {
    zh: "通道",
    en: "Channels",
    link: "26-channels.md",
    source: "26-channels.go",
  },
  {
    zh: "通道缓冲",
    en: "Channel Buffering",
    link: "27-channel-buffering.md",
    source: "27-channel-buffering.go",
  },
  {
    zh: "通道同步",
    en: "Channel Synchronization",
    link: "28-channel-synchronization.md",
    source: "28-channel-synchronization.go",
  },
  {
    zh: "通道方向",
    en: "Channel Directions",
    link: "29-channel-directions.md",
    source: "29-channel-directions.go",
  },
  {
    zh: "Select语句",
    en: "Select",
    link: "30-select.md",
    source: "30-select.go",
  },
  {
    zh: "超时处理",
    en: "Timeouts",
    link: "31-timeouts.md",
    source: "31-timeouts.go",
  },
  {
    zh: "非阻塞通道操作",
    en: "Non-Blocking Channel Operations",
    link: "32-non-blocking-channel-operations.md",
    source: "32-non-blocking-channel-operations.go",
  },
  {
    zh: "关闭通道",
    en: "Closing Channels",
    link: "33-closing-channels.md",
    source: "33-closing-channels.go",
  },
  {
    zh: "通过通道遍历",
    en: "Range over Channels",
    link: "34-range-over-channels.md",
    source: "34-range-over-channels.go",
  },
  { zh: "定时器", en: "Timers", link: "35-timers.md", source: "35-timers.go" },
  {
    zh: "定时触发器",
    en: "Tickers",
    link: "36-tickers.md",
    source: "36-tickers.go",
  },
  {
    zh: "工作池",
    en: "Worker Pools",
    link: "37-worker-pools.md",
    source: "37-worker-pools.go",
  },
  {
    zh: "等待组",
    en: "WaitGroups",
    link: "38-waitgroups.md",
    source: "38-waitgroups.go",
  },
  {
    zh: "限流",
    en: "Rate Limiting",
    link: "39-rate-limiting.md",
    source: "39-rate-limiting.go",
  },
  {
    zh: "原子计数器",
    en: "Atomic Counters",
    link: "40-atomic-counters.md",
    source: "40-atomic-counters.go",
  },
  {
    zh: "互斥锁",
    en: "Mutexes",
    link: "41-mutexes.md",
    source: "41-mutexes.go",
  },
  {
    zh: "有状态的Go协程",
    en: "Stateful Goroutines",
    link: "42-stateful-goroutines.md",
    source: "42-stateful-goroutines.go",
  },
  { zh: "排序", en: "Sorting", link: "43-sorting.md", source: "43-sorting.go" },
  {
    zh: "根据函数排序",
    en: "Sorting by Functions",
    link: "44-sorting-by-functions.md",
    source: "44-sorting-by-functions.go",
  },
  { zh: "异常处理", en: "Panic", link: "45-panic.md", source: "45-panic.go" },
  { zh: "延迟执行", en: "Defer", link: "46-defer.md", source: "46-defer.go" },
  {
    zh: "恢复异常",
    en: "Recover",
    link: "47-recover.md",
    source: "47-recover.go",
  },
  {
    zh: "字符串函数",
    en: "String Functions",
    link: "48-string-functions.md",
    source: "48-string-functions.go",
  },
  {
    zh: "字符串格式化",
    en: "String Formatting",
    link: "49-string-formatting.md",
    source: "49-string-formatting.go",
  },
  {
    zh: "文本模板",
    en: "Text Templates",
    link: "50-text-templates.md",
    source: "50-text-templates.go",
  },
  {
    zh: "正则表达式",
    en: "Regular Expressions",
    link: "51-regular-expressions.md",
    source: "51-regular-expressions.go",
  },
  { zh: "JSON", en: "JSON", link: "52-json.md", source: "52-json.go" },
  { zh: "XML", en: "XML", link: "53-xml.md", source: "53-xml.go" },
  { zh: "时间", en: "Time", link: "54-time.md", source: "54-time.go" },
  { zh: "纪元", en: "Epoch", link: "55-epoch.md", source: "55-epoch.go" },
  {
    zh: "时间格式化/解析",
    en: "Time Formatting / Parsing",
    link: "56-time-formatting-parsing.md",
    source: "56-time-formatting-parsing.go",
  },
  {
    zh: "随机数",
    en: "Random Numbers",
    link: "57-random-numbers.md",
    source: "57-random-numbers.go",
  },
  {
    zh: "数字解析",
    en: "Number Parsing",
    link: "58-number-parsing.md",
    source: "58-number-parsing.go",
  },
  {
    zh: "URL解析",
    en: "URL Parsing",
    link: "59-url-parsing.md",
    source: "59-url-parsing.go",
  },
  {
    zh: "SHA256哈希",
    en: "SHA256 Hashes",
    link: "60-sha256-hashes.md",
    source: "60-sha256-hashes.go",
  },
  {
    zh: "Base64编码",
    en: "Base64 Encoding",
    link: "61-base64-encoding.md",
    source: "61-base64-encoding.go",
  },
  {
    zh: "读取文件",
    en: "Reading Files",
    link: "62-reading-files.md",
    source: "62-reading-files.go",
  },
  {
    zh: "写入文件",
    en: "Writing Files",
    link: "63-writing-files.md",
    source: "63-writing-files.go",
  },
  {
    zh: "行过滤器",
    en: "Line Filters",
    link: "64-line-filters.md",
    source: "64-line-filters.go",
  },
  {
    zh: "文件路径",
    en: "File Paths",
    link: "65-file-paths.md",
    source: "65-file-paths.go",
  },
  {
    zh: "目录",
    en: "Directories",
    link: "66-directories.md",
    source: "66-directories.go",
  },
  {
    zh: "临时文件和目录",
    en: "Temporary Files and Directories",
    link: "67-temporary-files-and-directories.md",
    source: "67-temporary-files-and-directories.go",
  },
  {
    zh: "嵌入指令",
    en: "Embed Directive",
    link: "68-embed-directive.md",
    source: "68-embed-directive.go",
  },
  {
    zh: "测试和基准测试",
    en: "Testing and Benchmarking",
    link: "69-testing-and-benchmarking.md",
    source: "69-testing-and-benchmarking.go",
  },
  {
    zh: "命令行参数",
    en: "Command-Line Arguments",
    link: "70-command-line-arguments.md",
    source: "70-command-line-arguments.go",
  },
  {
    zh: "命令行标志",
    en: "Command-Line Flags",
    link: "71-command-line-flags.md",
    source: "71-command-line-flags.go",
  },
  {
    zh: "命令行子命令",
    en: "Command-Line Subcommands",
    link: "72-command-line-subcommands.md",
    source: "72-command-line-subcommands.go",
  },
  {
    zh: "环境变量",
    en: "Environment Variables",
    link: "73-environment-variables.md",
    source: "73-environment-variables.go",
  },
  {
    zh: "日志记录",
    en: "Logging",
    link: "74-logging.md",
    source: "74-logging.go",
  },
  {
    zh: "HTTP客户端",
    en: "HTTP Client",
    link: "75-http-client.md",
    source: "75-http-client.go",
  },
  {
    zh: "HTTP服务器",
    en: "HTTP Server",
    link: "76-http-server.md",
    source: "76-http-server.go",
  },
  {
    zh: "上下文",
    en: "Context",
    link: "77-context.md",
    source: "77-context.go",
  },
  {
    zh: "启动进程",
    en: "Spawning Processes",
    link: "78-spawning-processes.md",
    source: "78-spawning-processes.go",
  },
  {
    zh: "执行进程",
    en: "Exec'ing Processes",
    link: "79-exec-ing-processes.md",
    source: "79-exec-ing-processes.go",
  },
  { zh: "信号", en: "Signals", link: "80-signals.md", source: "80-signals.go" },
  { zh: "退出", en: "Exit", link: "81-exit.md", source: "81-exit.go" },
];

export const markDocRaw = docList.reduce((acc, item, idx) => {
  acc[item.link] = item;
  return acc;
}, {});

export const buildSidebar = [
  { text: "介绍", link: "/introduction" },
  {
    text: "开始",
    items: docList.map(({ zh, en, link }) => {
      return {
        text: en == zh ? en : `${zh}(${en})`,
        link: `/docs/${link}`,
      };
    }),
  },
];
